AWSTemplateFormatVersion: '2010-09-09'
Description: Enable Inspector, GuardDuty, Security Hub, and create read-only IAM for Phoenix Security.

Resources:

  EnableSecurityHub:
    Type: AWS::SecurityHub::Hub
    Properties: {}

  GuardDutyDetector:
    Type: AWS::GuardDuty::Detector
    Properties:
      Enable: true

  ReadOnlyUser:
    Type: AWS::IAM::User
    Properties:
      UserName: phoenix-security-reader

  AttachReadOnlyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: SecurityHubReadOnlyAccess
      Users:
        - Ref: ReadOnlyUser
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - "securityhub:Describe*"
              - "securityhub:Get*"
              - "securityhub:List*"
            Resource: "*"

  AccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref ReadOnlyUser

Outputs:
  AccessKeyID:
    Value: !Ref AccessKey
  SecretAccessKey:
    Value: !GetAtt AccessKey.SecretAccessKey